### ISSUE TITLE
Demande d'amélioration

### ISSUE THREAD

**Issue by romainbriand** [grocanar/GedcomforGeneanet#1]
Bonjour,
J'utilise beaucoup la fonctionnalité "Noms alternatifs" de Gramps pour les orthographes alternatives du nom d'une même personne.
Dans l'export Gedcom, ces noms de famille alternatifs sont renvoyés entourés de slashes
```
0 @I1187@ INDI
1 NAME Anne /Gats/
2 GIVN Anne
2 SURN Gats
1 NAME Anne /Gaz/
2 GIVN Anne
2 SURN Gaz
1 NAME Anne /Gatz/
2 GIVN Anne
2 SURN Gatz
1 SEX F
1 BIRT
2 DATE 11 JUN 1778
```
Et notre ami Geneanet ne le traite pas correctement lors de l'import, ce qui donne des choses étranges à l'affichage ([voir le rendu ici](https://gw.geneanet.org/briandromain_w?lang=fr&n=gats&nz=briand&oc=0&ocz=0&p=anne&pz=romain+mickael+christophe&type=fiche))

Serait-il possible d'inclure un petit traitement pour supprimer ces slashes de l'export Gedcom?
Merci d'avance et encore merci pour cette super extension !

**Comment by grocanar** [comment]
Bonjour

En effet c'est le cas mais par manque de "courage" je m'en etais accomodé.

Avez vous posez la question sur le forum geneanet?

en effet il n'y a pas de raisons que cela soit traite dans le premiere 
occurence du tag NAME et pas

dans les suivantes.

je traiterais ce cas particulier si ils refusent de corriger mais cela 
serait quand meme preferable que cela soit

fixé au niveau de geneanet.

quand j implemente une exception j'ai toujours demande avant a geneanet 
si ils pouvaient traiter le cas.

le mieux est de ne pas faire trop gonfler mon extension.

Si vous le desirez je peux poser la question moi meme.


Cordialement


Le 08/09/2018 à 15:36, Romain Briand a écrit :

**Comment by grocanar** [comment]
finalement j'ai poste la question dans le forum geneanet
n'hesitez pas a renforcer mon propos :)
https://www.geneanet.org/forum/viewtopic.php?f=11&t=603501

Le 08/09/2018 à 15:36, Romain Briand a écrit :

**Comment by romainbriand** [comment]
@grocanar : j'ai appuyé la demande comme demandé :) https://www.geneanet.org/forum/viewtopic.php?f=11&t=603501&p=1403179#p1403179

**Comment by grocanar** [comment]
J'ai regle le "problème" dans la derniere version
