### ISSUE TITLE
README.md à corriger

### ISSUE THREAD

**Issue by TitiFix** [grocanar/GedcomforGeneanet#2]
Bonjour,
Il faudrait corriger le README.md
 
> Pour utiliser ce greffons il faut télécharger le fichier zip de la version souhaité et
> Sous unix dezipper le fichier dans le répertoire $HOME/.gramps/gramps42/plugins/
> Sous Windows deippter le fichiers dans le répertoire 
> C:\Users<~username>\AppData\Roaming\gramps\gramps42\plugins

en

> Pour utiliser ce **greffon** il faut télécharger le fichier zip de la version **souhaitée (avec XX = 42, 50, …)** et
> Sous unix dezipper le fichier dans le répertoire $HOME/.gramps/grampsXX/plugins/
> Sous Windows **dezipper** le fichiers dans le répertoire 
> **%USERPROFILE%**\AppData\Roaming\gramps\grampsXX\plugins

ou quelque chose du genre pour :
- prendre en compte la version de Gramps dans les chemins (j'ai bêtement essayé de copier le plugin 5.0 dans le répertoire 4.2...)
- pour Windows utiliser plutôt userprofile pour prendre en compte que certaines installations ne sont pas forçement sur C:\users (même si c'est le plus courant)

Cordialement
Thierry ETIENNE

**Comment by grocanar** [comment]
Je viens de faire la correction en decouvrant l'issue. 
merci d'avoir remonter

**Comment by TitiFix** [comment]
Merci,
A  noter qu'il faut corriger la modification car comme je l'ai indiqué %USERPROFILE% _inclus le nom du user._
sous windows USERPROFILE = C:\Users\%USERNAME%

il faut copier dans %USERPROFILE%\AppData\Roaming\gramps\grampsXX\plugins
