### ISSUE TITLE
Note Installation sous Windows à ajuster

### ISSUE THREAD

**Issue by TitiFix** [grocanar/GedcomforGeneanet#4]
Bonjour Eric,
Il est indiqué dans readme.md

> Sous Windows dezipper le fichiers dans le répertoire %USERPROFILE%
> **<~username>**\AppData\Roaming\gramps\grampsXX\plugins En général la variable %USERPROFILE% vaut **C:\Users**
> 

Il faudrait écrire  

> Sous Windows dezipper le fichiers dans le répertoire **%USERPROFILE%\AppData**\Roaming\gramps\grampsXX\plugins.
> En général la variable %USERPROFILE% vaut C:\Users\\**%USERNAME%**
>

**Comment by grocanar** [comment]
Mais au final le chemin est le meme nom? 
Je dois avouer que les subtilites sur lavaleur de %USERPROFILE% dans windows me sont assez eloignées

**Comment by TitiFix** [comment]
Bonjour Eric,
Oui, il faut savoir aussi que AppData est un répertoire caché non accessible naturellement
%USERPROFILE%\AppData\... == C:\USER\nom_compte_utilisateur\AppData\...
USERPROFILE contient le nom de l'utilisateur

A la réflexion, Il y a aussi la variable APPDATA (APPDATA = %USERPROFILE%\AppData\Roaming)  ; c'est même plus simple d'indiquer

> Sous Windows dezipper le fichier dans le répertoire %APPDATA%\gramps\grampsXX\plugins
> (APPDATA vaut par défaut C:\USER\\%USERNAME%\AppData\Roaming avec %USERNAME% le nom de l'utilisateur sous Windows 10)
> 

Cela permet de s'affranchir de la version de Windows (on le contenu de APPDATA peut être différent dans les anciennes versions)

Thierry

**Comment by TitiFix** [comment]
Bonjour Eric,
Il faudrait aussi préciser dans la section "installation" qu'il faut quitter Gramp avant de copier le Zip. Sinon si le greffon précédent a été utilisé avant la copie, c'est toujours lui qui est en mémoire.

Cordialement
Thierry

**Comment by grocanar** [comment]
j'ai fait les corrections

**Comment by TitiFix** [comment]
c'est bon, a noter qu'il reste toujours la description de l'option "Suppression de la structure adresse optionnelle"
