### ISSUE TITLE
Erreur tag FILE dans header si option "chemin relatif"

### ISSUE THREAD

**Issue by TitiFix** [grocanar/GedcomforGeneanet#5]
Bonjour Eric,

il y a une erreur dans la production du header gedcom (fonction _header ) si l'option "chemin relatif des médias" est activée
>         if self.relativepath:
>             filenam = os.path.basename(filename)
>             self._writeln(1, "FILE2", filenam, limit=255)
Il y a un 2 en trop après FILE à la ligne 1059 (V2.0.12)
je ne pense pas que cela gène quelqu'un mais c'est à corriger à l'occasion

Cordialement
Thierry

**Comment by grocanar** [comment]
fix in current release
